language: python
python:
    - "3.6"
branches:
    only:
        - master
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-coverage test_minesweeper.py
after_success:
    - coveralls
